# Generated by Django 5.0.2 on 2024-02-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='restrictions',
            new_name='for_whom',
        ),
    ]
