# Generated by Django 5.0.2 on 2024-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_rename_restrictions_organization_for_whom'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='county',
            field=models.CharField(default='Washtenaw', max_length=200),
            preserve_default=False,
        ),
    ]
