name: _2marines_online
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core for initializing Firebase
  firebase_core: ^3.6.0  # Replace with the latest version

  # Firebase authentication for user login, signup, etc.
  firebase_auth: ^5.3.1  # Replace with the latest version

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. 
  flutter_lints: ^5.0.0

flutter:

  # Ensure that the Material Icons font is included.
  uses-material-design: true

  # To add assets to your application, uncomment the following lines:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts, uncomment the following lines:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
